### ISSUE TITLE
Support STM32 Board just like NAZE32 or SPRACINGF3

### ISSUE THREAD

**Issue by Linjieqiang** [MatrixPilot/MatrixPilot#172]
I am a rc fans, I love flying the fixedwing, can MatrixPilot project support STM32 Board just like NAZE32?

**Comment by phollands** [comment]
Not supported Today. Although Robert has done quite a bit of work on making the code portable to  ARM architectures. But it is not released and tested as far as I know.

 MatrixPilot is predominantly running on the Microchip dspic architectures.

**Comment by Inspirati** [comment]
Thanks Pete, however my efforts were truly just as you suggest, aka,
towards making the build system somewhat compatible. Credit for the STM32F
series work belongs with LeoG, whom strode somewhat forwards toward making
it work (aka, he sent me his work, in terms of hardware home made adapter
boards!!), alas but alas, nobody else here followed....

**Comment by Linjieqiang** [comment]
That's a big pity.Thanks.Hope that day coming.
