### ISSUE TITLE
New warning on default project build

### ISSUE THREAD

**Issue by elgarbe** [MatrixPilot/MatrixPilot#63]
Hi I just pull last changes to my local copy and manully change options.h
I forget to uncoment this [line](https://github.com/MatrixPilot/MatrixPilot/blob/master/Config/options.h#L365)

and so get this warning:
../../MatrixPilot/telemetry.c: In function 'telemetry_init':
../../MatrixPilot/telemetry.c:134:2: warning: #warning SERIAL_BAUDRATE set to default value of 19200 bps

**Comment by phollands** [comment]
Fixed in master[ by this commit ](https://github.com/MatrixPilot/MatrixPilot/commit/9559ff544cb071958134eded4fede7961317e6db)
