### ISSUE TITLE
Can't process waypoint.h in Windows

### ISSUE THREAD

**Issue by elgarbe** [MatrixPilot/MatrixPilot#81]
Hi, flan gives me an error when I activate waypoint.h and pointed to flight-waypoint.h

[This is the error I get](https://www.dropbox.com/s/8o5yjxzo4h26jpq/Captura%20de%20pantalla%202016-10-14%2012.49.32.png?dl=0)

Best Wishes, Leo

**Comment by phollands** [comment]
Hi Leo,

Thanks for pointing out this out.

Now that we have moved to MPLAB-X, some users, like yourself, no longer have MPLAB installed. Flan.pyw has been using the C macro pre-processor supplied by Microchip, when analysing a waypoints.h file under Windows. It cannot find the C pre-processor on your installation, as it does not yet know about the MPLAB-X pre-processor.

I'll take a look at flan.pyw to see if there is an obvious solution. It takes about a day for my Windows laptop to get fully start ( microsoft updates, virus updates etc), so it may be a while before I get to this.  You can de-activate the analysis of waypoints.h file in flan.pyw for the time being, if you just want to view your flights in GooglEarth without the waypoints embedded. 

Best wishes, Pete
